version: '3.8'

services:
  app:
    build:
      context: ./www/
      dockerfile: Dockerfile.php
    image: image_php:${TAG:-latest}
    container_name: conteneur_php
    ports:
      - "80:80"
    networks:
      - docker_network

  db:
    build:
      context: ./database/
      dockerfile: Dockerfile.mysql
    image: image_mysql:${TAG:-latest}
    container_name: conteneur_mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gestion_produits
    networks:
      - docker_network

networks:
  docker_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
